In [2]:
import pandas as pd
import numpy as np
import seaborn as sns

# Q2. Records count
How many records are in the dataset?

A. 5000
B. 9000
C. 10000
D. 15000

In [3]:
df = pd.read_csv('https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv')

In [5]:
df.head(5)

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0

In [8]:
df.shape

(10000, 11)

# Q3. Fuel types

How many fuel types are presented in the dataset?

A. 1

B. 2

C. 3

D. 4

In [24]:
df['fuel_type'].unique()

<StringArray>
['Gasoline', 'Diesel', 'Hybrid']
Length: 3, dtype: str

# Q4. Missing values
How many columns in the dataset have missing values?

A. 0

B. 1

C. 2

D. 3

E. 4

In [12]:
df.isna().sum()

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

# Q6. Median value of horsepower

Find the median value of the horsepower column in the dataset.
Next, calculate the most frequent value of the same horsepower column.
Use the fillna method to fill the missing values in the horsepower column with the most frequent value from the previous step.
Now, calculate the median value of horsepower once again.
Has it changed?

Yes, it increased
Yes, it decreased
No

In [14]:
horsepower_mid_rep = df["horsepower"].fillna(df["horsepower"].median(), inplace=True)

/tmp/ipykernel_45321/457730235.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  horsepower_mid_rep = df["horsepower"].fillna(df["horsepower"].median(), inplace=True)

In [15]:
horsepower_mid_rep.head(7)

0    243.0
1    272.0
2    267.0
3    258.0
4    304.0
5    266.0
6    250.0
Name: horsepower, dtype: float64

In [26]:
horsepower_mid_rep.median()

np.float64(254.0)

In [16]:
df["horsepower"].mode()

0    252.0
Name: horsepower, dtype: float64

In [17]:
df["horsepower"].median()

np.float64(254.0)

# Q5. Max fuel efficiency
What's the maximum fuel efficiency of cars from Asia?

A. 21.2

B. 31.2

C. 41.2

D. 51.2

In [18]:
df.groupby('origin')["fuel_efficiency_mpg"].max()

origin
Asia      41.2
Europe    39.4
USA       38.2
Name: fuel_efficiency_mpg, dtype: float64

In [19]:
df["origin"].isna().sum()

np.int64(0)

In [20]:
df["origin"].unique()

<StringArray>
['Europe', 'Asia', 'USA']
Length: 3, dtype: str

In [21]:
df['model_year'].isna().sum()

np.int64(0)

In [22]:
df['fuel_type'].isna().sum()

np.int64(0)

In [23]:
df.isna().sum()

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

# Q7. Sum of weights

1. Select all the cars from Asia
2. Select only columns vehicle_weight and model_year

3. Select the first 7 values

4. Get the underlying NumPy array. Let's call it X.

5. Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
Invert XTX.

6. Create an array y with values [1100, 1300, 800, 900, 1000, 1100, 1200].

7. Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.

8. What's the sum of all the elements of the result?
Note: You just implemented linear regression. We'll talk about it in the next lesson.

Options:

A. 0.0369

B. 0.369

C. 3.69

D. 36.9

In [27]:
df.head(3)

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5

In [30]:
Asian_vehicles=df.loc[df['origin'] == 'Asia'][['vehicle_weight', 'model_year']]

In [35]:
X = np.asarray(Asian_vehicles.head(7))
X

array([[4240, 1996],
       [4310, 1992],
       [4230, 1997],
       [4420, 1978],
       [3950, 2007],
       [4750, 2021],
       [4450, 2019]])

In [56]:
XT = X.transpose()
XT

array([[4240, 4310, 4230, 4420, 3950, 4750, 4450],
       [1996, 1992, 1997, 1978, 2007, 2021, 2019]])

In [57]:
X.T

array([[4240, 4310, 4230, 4420, 3950, 4750, 4450],
       [1996, 1992, 1997, 1978, 2007, 2021, 2019]])

In [58]:
XTX = np.matmul(XT, X)
XTX

array([[131950500,  60750580],
       [ 60750580,  28041424]])

In [59]:
inv_XTX = np.linalg.inv(XTX)

In [63]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

In [66]:
w = inv_XTX @ XT @ y

In [67]:
w.sum()

np.float64(0.36919696904925486)